# Generated by Django 3.1.7 on 2021-04-07 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210407_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='task_duedate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 16, 45, 12, 260556)),
        ),
    ]
