# Generated by Django 3.1.5 on 2021-01-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210129_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_name',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_name',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_name',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
