# Generated by Django 3.1.7 on 2021-04-07 10:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210130_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instagram_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Task_List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(blank=True, editable=False, max_length=20)),
                ('task_description', models.CharField(blank=True, max_length=700)),
                ('task_completed', models.BooleanField(default=False)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_duedate', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 16, 15, 19, 298777))),
                ('task_accepted', models.BooleanField(default=True)),
                ('task_doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doer', to=settings.AUTH_USER_MODEL)),
                ('task_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
