# Generated by Django 3.1.7 on 2021-04-07 11:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210407_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='task_duedate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 16, 44, 39, 550511)),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
