# Generated by Django 3.1.7 on 2021-04-07 11:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210407_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='task_duedate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 17, 26, 46, 467773)),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='task_sender',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
