# Generated by Django 3.2.3 on 2021-05-26 06:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210407_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_list',
            name='task_accepted',
        ),
        migrations.RemoveField(
            model_name='task_list',
            name='task_sender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_name',
        ),
        migrations.AlterField(
            model_name='task_list',
            name='task_duedate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 12, 4, 15, 896864)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
