# Generated by Django 3.2.3 on 2021-05-26 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_task_list_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='task_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='task_duedate',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 16, 27, 41, 339636)),
        ),
    ]
