# Generated by Django 3.2.3 on 2021-05-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_task_list_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='task_duedate',
            field=models.DateTimeField(max_length=20),
        ),
    ]
