# Generated by Django 3.2.3 on 2021-05-27 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_task_list_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='task_duedate',
            field=models.DateField(default=datetime.date(2021, 5, 27)),
        ),
    ]
